name: Deploy Docusaurus Site

on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'  

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # O branch no GitHub onde o site será hospedado
        folder: build  # O diretório gerado pelo comando build do Docusaurus
        token: ${{ secrets.GITHUB_TOKEN }}  # Token para autorizar o deploy
